# Generated by Django 5.2.8 on 2026-03-12 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_cart_unique_together_delete_basketitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='photo',
            field=models.ImageField(upload_to='category/'),
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
    ]
